name: barikoi_sdk
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  barikoi_maps_place_picker:
    git:
      url: https://github.com/barikoi/barikoi_map_place_picker.git
      ref: master
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  geolocator: ^12.0.0
  http: ^1.2.2
  intl: ^0.19.0
  maplibre_gl: 0.19.0+2

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
